[book]
authors = ["Jelle Vos"]
language = "en"
multilingual = false
src = "src"
title = "Crypto Catalog"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/jellevos/crypto-catalog"

